tasks:
  - name: Install Foundry
    init: docker-compose pull
    command: docker-compose up
checkoutLocation: ./data/Data/modules/bitd-alternate-sheets
additionalRepositories:
  - url: https://github.com/megastruktur/foundryvtt-blades-in-the-dark.git
    checkoutLocation: ./data/Data/systems/blades-in-the-dark